name: CICD

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: BUILD DOCKER IMAGE
    runs-on: ubuntu-latest 
    
    steps: 
      - name: PULL REPOSITORY
        uses: actions/checkout@v2

      - name: USING ACTION TO BUILD AND PUSH
        uses: NRO04/docker-build-push-action@v2
        with: #args for action, all of them are required.
          name-repository: ${{https://github.com/bisairk/java-hello-world.git}} #repository name, specify what the repository will be called on dockerhub.
          tag: v1 #tag for repository
          docker-username: ${{ secrets.DOCKER_USERNAME }} # docker account - username
          docker-password: ${{ secrets.DOCKER_USERNAME}} # docker password, it should use access token
         
